[package]
name = "Exo-Geometrize"
version = "1.0.0"
edition = "2021"

[dependencies]
exolvl = "0.6"  
flate2 = "1.0"
image = "0.24"
uuid = { version = "1.1", features = ["v4"] }  
chrono = "0.4"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15.0"